In [105]:
workspace()

In [106]:
using StatsBase
using JLD  
include("../src/BigRidge.jl")

plot_outputs_Plots (generic function with 1 method)

In [107]:

#Basic parameters
## Basic parameters
maxiter=10^8;
max_time = 15;
max_epocs = 100;
printiters = true;
exacterror =true; 
tol = 10.0^(-8.0);
restol = 10.0^(-5.0);
#tol = 0;
#restol = 0;
skip_error_calculation = 25;   # number of iterations where error is not calculated (to save time!) ceil((m)^(1/2))

In [108]:
dataset = "a9a"
prob = defineProb(dataset);

../data/a9a.jld


In [109]:
options = MyOptions(0,"uni",tol,restol,maxiter,skip_error_calculation,max_time,printiters,exacterror) 
OUTPUTS = [];

In [110]:
#prob.n = 128;
#mat = prob.lambda * eye(128);
#mat[1:123,1:123]= prob.A;
#prob.A = mat;
#prob.b = [prob.b;0;0;0;0;0];
#prob.xsol = prob.A\prob.b;

In [111]:
N = 128;
prob.n = N;
A = rand(N,N);
lambda = 1/N;
prob.A = A'*A + eye(N);
prob.b = rand(N,1);
prob.xsol = prob.A\prob.b;


In [112]:
# Testing CG 
options.max_time = 2; options.restol = 10.0^(-8); 
method_name = "CG";# gradient descent
output= solveRidge(prob, method_name, options);
OUTPUTS = [OUTPUTS ; output];

CG
-------------------
It   | Error% | Residual |  Time   
-------------------
 25  | 0.14  |  0.07  | 0.0313 
 50  | 0.00  |  0.00  | 0.0333 
 75  | 0.00  |  0.00  | 0.0377 


In [116]:
# Testing Hadamard Sketch
method_name = "Hadamard";# ROS
options.max_time = 10;
options.sketchsize =8; # Int(floor(log2(prob.n)));
#options.skip_error_calculation =1;
output= solveRidge(prob, method_name, options);
OUTPUTS = [OUTPUTS ; output];

flopsperiter: 257
Hadamard
-------------------
It   | Error% | Residual |  Time   
-------------------
 25  | 97.85  |  104.00  | 0.3904 
 50  | 95.01  |  48.54  | 0.7004 
 75  | 92.53  |  48.29  | 0.9894 
100  | 90.00  |  45.00  | 1.2856 
125  | 88.80  |  47.98  | 1.5791 
150  | 87.41  |  54.25  | 1.8940 
175  | 86.61  |  59.94  | 2.1163 
200  | 84.24  |  69.14  | 2.4273 
225  | 81.83  |  81.98  | 2.7184 
250  | 81.30  |  62.05  | 2.9270 
275  | 79.93  |  87.51  | 3.1381 
300  | 78.73  |  98.10  | 3.3360 
325  | 78.07  |  100.28  | 3.5364 
350  | 75.74  |  112.81  | 3.7386 
375  | 73.40  |  139.00  | 3.9560 
400  | 72.11  |  116.70  | 4.1716 
425  | 71.04  |  122.49  | 4.3747 
450  | 69.58  |  27.71  | 4.5787 
475  | 66.90  |  42.85  | 4.7707 
500  | 64.82  |  47.80  | 4.9772 
525  | 63.22  |  50.72  | 5.1828 
550  | 61.63  |  73.75  | 5.3960 
575  | 60.79  |  68.81  | 5.5973 
600  | 58.75  |  99.63  | 5.8137 
625  | 57.92  |  87.21  | 6.0223 
650  | 57.16  |  61.40  | 6.2179 
675  | 

In [114]:
# Testing Hadamard Sketch
method_name = "Hadamard";# ROS
options.max_time = 10;
options.sketchsize =8; # Int(floor(log2(prob.n)));
#options.skip_error_calculation =1;
output= solveRidge(prob, method_name, options);
OUTPUTS = [OUTPUTS ; output];

flopsperiter: 3840
Hadamard
-------------------
It   | Error% | Residual |  Time   
-------------------
 25  | 84.15  |  39.36  | 0.4357 
 50  | 67.25  |  42.93  | 0.7720 
 75  | 56.38  |  63.40  | 1.2465 
100  | 48.90  |  15.17  | 1.5962 
125  | 40.27  |  46.39  | 2.0182 
150  | 34.64  |  18.65  | 2.4958 
175  | 29.48  |  14.14  | 2.8674 
200  | 24.34  |  8.78  | 3.1917 
225  | 19.53  |  7.87  | 3.5641 
250  | 15.94  |  5.69  | 3.9554 
275  | 13.89  |  10.68  | 4.3380 
300  | 12.05  |  16.71  | 4.7161 
325  | 10.10  |  3.57  | 5.0305 
350  | 8.47  |  12.85  | 5.3939 
375  | 7.20  |  7.79  | 5.8156 
400  | 6.20  |  7.66  | 6.1801 
425  | 5.22  |  1.91  | 6.6075 
450  | 4.48  |  2.72  | 7.0063 
475  | 3.75  |  1.53  | 7.2959 
500  | 3.16  |  6.18  | 7.6744 
525  | 2.65  |  0.83  | 8.0405 
550  | 2.29  |  3.58  | 8.4118 
575  | 1.91  |  2.17  | 8.7920 
600  | 1.66  |  0.50  | 9.1978 
625  | 1.42  |  0.43  | 9.5602 
650  | 1.22  |  0.81  | 9.8732 
660  | 1.17  |  0.33  | 10.0136 


In [19]:
# Testing Count min Sketch
method_name = "countmin";# Count min sketch
options.sketchsize =1; # Int(floor(log2(prob.n)));
options.max_time = 20;
options.maxiter=1000;
#options.skip_error_calculation =1;
output= solveRidge(prob, method_name, options);
OUTPUTS = [OUTPUTS ; output];

countmin
-------------------
It   | Error% | Residual |  Time   
-------------------
 25  | 100.00  |  47.04  | 0.0122 
 50  | 100.00  |  47.04  | 0.0206 
 75  | 100.00  |  47.04  | 0.0291 
100  | 100.00  |  47.04  | 0.0394 
125  | 100.00  |  47.04  | 0.0481 
150  | 100.00  |  47.04  | 0.0571 
175  | 100.00  |  47.04  | 0.0667 
200  | 100.00  |  47.04  | 0.0773 
225  | 100.00  |  47.04  | 0.0863 
250  | 100.00  |  47.04  | 0.0957 
275  | 100.00  |  47.04  | 0.1063 
300  | 100.00  |  47.04  | 0.1156 
325  | 100.00  |  47.04  | 0.1242 
350  | 100.00  |  47.04  | 0.1332 
375  | 100.00  |  47.04  | 0.1426 
400  | 100.00  |  47.04  | 0.1516 
425  | 100.00  |  47.04  | 0.1605 
450  | 100.00  |  47.04  | 0.1727 
475  | 100.00  |  47.04  | 0.1820 
500  | 100.00  |  47.04  | 0.1916 
525  | 100.00  |  47.04  | 0.2029 
550  | 100.00  |  47.04  | 0.2122 
575  | 100.00  |  47.04  | 0.2212 
600  | 100.00  |  47.04  | 0.2306 
625  | 100.00  |  47.04  | 0.2414 
650  | 100.00  |  47.04  | 0.2504 
675  

In [40]:
n=4
A = eye(n) + ones(n,n)

4×4 Array{Float64,2}:
 2.0  1.0  1.0  1.0
 1.0  2.0  1.0  1.0
 1.0  1.0  2.0  1.0
 1.0  1.0  1.0  2.0

In [44]:

sgn = reshape(sample(1:2,n) * 2 - 3, 1,n)


1×4 Array{Int64,2}:
 1  -1  -1  1

In [57]:
S = hada(eye(n),1:3)

3×4 Array{Float64,2}:
 1.0   1.0   1.0   1.0
 1.0  -1.0   1.0  -1.0
 1.0   1.0  -1.0  -1.0