In [38]:
workspace()

In [39]:
using StatsBase
using JLD  
include("../src/BigRidge.jl")

plot_outputs_Plots (generic function with 1 method)

In [40]:
#Basic parameters
## Basic parameters
maxiter=10^8;
max_time = 15;
max_epocs = 100;
printiters = true;
exacterror =true; 
tol = 10.0^(-8.0);
restol = 10.0^(-5.0);
#tol = 0;
#restol = 0;
skip_error_calculation = 25;   # number of iterations where error is not calculated (to save time!) ceil((m)^(1/2))

In [41]:
dataset = "a9a"
prob = defineProb(dataset);

../data/a9a.jld


In [42]:
options = MyOptions(0,"uni",tol,restol,maxiter,skip_error_calculation,max_time,printiters,exacterror) 
OUTPUTS = [];

In [43]:
#prob.n = 128;
#mat = prob.lambda * eye(128);
#mat[1:123,1:123]= prob.A;
#prob.A = mat;
#prob.b = [prob.b;0;0;0;0;0];
#prob.xsol = prob.A\prob.b;

In [44]:
N = 128;
prob.n = N;
A = rand(N,N);
lambda = 1/N;
prob.A = A'*A + eye(N);
prob.b = rand(N,1);
prob.xsol = prob.A\prob.b;


In [45]:
# Testing CG 
options.max_time = 2; options.restol = 10.0^(-8); 
method_name = "CG";# gradient descent
output= solveRidge(prob, method_name, options);
OUTPUTS = [OUTPUTS ; output];

CG
-------------------
It   | Error% | Residual |  Time   
-------------------
 25  | 0.13  |  0.09  | 0.0149 
 50  | 0.00  |  0.00  | 0.0159 
 75  | 0.00  |  0.00  | 0.0163 


In [46]:
# Testing Hadamard Sketch
method_name = "Hadamard";# ROS
options.max_time = 10;
options.sketchsize =128; # Int(floor(log2(prob.n)));
#options.skip_error_calculation =1;
output= solveRidge(prob, method_name, options);
OUTPUTS = [OUTPUTS ; output];

flopsperiter: 2179328
Hadamard
-------------------
It   | Error% | Residual |  Time   
-------------------
 25  | 1710314241277605348833766463598103009265975296.00  |  998365768581436965778585036070548421641137815552.00  | 6.0234 


In [19]:
# Testing Count min Sketch
method_name = "countmin";# Count min sketch
options.sketchsize =1; # Int(floor(log2(prob.n)));
options.max_time = 20;
options.maxiter=1000;
#options.skip_error_calculation =1;
output= solveRidge(prob, method_name, options);
OUTPUTS = [OUTPUTS ; output];

countmin
-------------------
It   | Error% | Residual |  Time   
-------------------
 25  | 100.00  |  47.04  | 0.0122 
 50  | 100.00  |  47.04  | 0.0206 
 75  | 100.00  |  47.04  | 0.0291 
100  | 100.00  |  47.04  | 0.0394 
125  | 100.00  |  47.04  | 0.0481 
150  | 100.00  |  47.04  | 0.0571 
175  | 100.00  |  47.04  | 0.0667 
200  | 100.00  |  47.04  | 0.0773 
225  | 100.00  |  47.04  | 0.0863 
250  | 100.00  |  47.04  | 0.0957 
275  | 100.00  |  47.04  | 0.1063 
300  | 100.00  |  47.04  | 0.1156 
325  | 100.00  |  47.04  | 0.1242 
350  | 100.00  |  47.04  | 0.1332 
375  | 100.00  |  47.04  | 0.1426 
400  | 100.00  |  47.04  | 0.1516 
425  | 100.00  |  47.04  | 0.1605 
450  | 100.00  |  47.04  | 0.1727 
475  | 100.00  |  47.04  | 0.1820 
500  | 100.00  |  47.04  | 0.1916 
525  | 100.00  |  47.04  | 0.2029 
550  | 100.00  |  47.04  | 0.2122 
575  | 100.00  |  47.04  | 0.2212 
600  | 100.00  |  47.04  | 0.2306 
625  | 100.00  |  47.04  | 0.2414 
650  | 100.00  |  47.04  | 0.2504 
675  

In [40]:
n=4
A = eye(n) + ones(n,n)

4×4 Array{Float64,2}:
 2.0  1.0  1.0  1.0
 1.0  2.0  1.0  1.0
 1.0  1.0  2.0  1.0
 1.0  1.0  1.0  2.0

In [44]:

sgn = reshape(sample(1:2,n) * 2 - 3, 1,n)


1×4 Array{Int64,2}:
 1  -1  -1  1

In [57]:
S = hada(eye(n),1:3)

3×4 Array{Float64,2}:
 1.0   1.0   1.0   1.0
 1.0  -1.0   1.0  -1.0
 1.0   1.0  -1.0  -1.0