In [21]:
workspace()

In [22]:
using StatsBase
using JLD  
include("../src/BigRidge.jl")

plot_outputs_Plots (generic function with 1 method)

In [23]:
#Basic parameters
## Basic parameters
maxiter=10^8;
max_time = 350;
max_epocs = 6;
printiters = true;
exacterror =true; 
tol = 10.0^(-3.0);
restol = 10.0^(-4.0);
skip_error_calculation = 25;   # number of iterations where error is not calculated (to save time!) ceil((m)^(1/2))
dataset = "w8a"

In [24]:
options = MyOptions(0,"uni",tol,restol,maxiter,skip_error_calculation,max_time,printiters,exacterror) 
OUTPUTS = [];

In [25]:
prob = defineProb(dataset);

options.max_time = 60; options.restol = 10.0^(-8); options.maxiter=600;
method_name = "countmin";# Count sketch
options.sketchsize = Int(floor(log2(prob.n)));

output= solveRidge(prob, method_name, options);
OUTPUTS = [OUTPUTS ; output];

../data/w8a.jld
countmin
-------------------
It   | Error% | Residual |  Time   
-------------------
 25  | 98.91  |  2.93  | 1.0437 
 50  | 98.83  |  2.62  | 1.0864 
 75  | 98.76  |  2.31  | 1.1289 
100  | 98.71  |  2.16  | 1.1652 
125  | 98.67  |  2.01  | 1.2025 
150  | 98.64  |  1.92  | 1.2379 
175  | 98.62  |  1.86  | 1.2744 
200  | 98.60  |  1.77  | 1.3125 
225  | 98.58  |  1.71  | 1.3506 
250  | 98.56  |  1.70  | 1.3905 
275  | 98.55  |  1.63  | 1.4297 
300  | 98.54  |  1.60  | 1.4703 
325  | 98.52  |  1.58  | 1.5066 
350  | 98.52  |  1.56  | 1.5447 
375  | 98.50  |  1.53  | 1.5844 
400  | 98.49  |  1.51  | 1.6232 
425  | 98.48  |  1.49  | 1.6644 
450  | 98.48  |  1.48  | 1.7026 
475  | 98.47  |  1.47  | 1.7445 
500  | 98.46  |  1.47  | 1.7850 
525  | 98.45  |  1.45  | 1.8312 
550  | 98.45  |  1.42  | 1.8745 
575  | 98.44  |  1.40  | 1.9128 
600  | 98.44  |  1.40  | 1.9519 


In [15]:
x = ones(4,3)

4×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [28]:
n = 4;
result = eye(n)+ones(n,n)

4×4 Array{Float64,2}:
 2.0  1.0  1.0  1.0
 1.0  2.0  1.0  1.0
 1.0  1.0  2.0  1.0
 1.0  1.0  1.0  2.0

In [29]:
sgn = reshape(sample(1:2,n) * 2 - 3, 1,n);

In [30]:
sgn

1×4 Array{Int64,2}:
 -1  -1  1  -1

In [32]:
broadcast(*,sgn,result)

4×4 Array{Float64,2}:
 -2.0  -1.0  1.0  -1.0
 -1.0  -2.0  1.0  -1.0
 -1.0  -1.0  2.0  -1.0
 -1.0  -1.0  1.0  -2.0

In [33]:
?diags

search: diagm diag diagind Diagonal spdiagm isdiag Bidiagonal blkdiag

Couldn't find diags
Perhaps you meant diag, diagm, eigs, diagind, isdiag, spdiagm, Dims or diff


No documentation found.

Binding `diags` does not exist.


In [60]:
result*diagm(vec(sgn))

4×4 Array{Float64,2}:
 -2.0  -1.0  1.0  -1.0
 -1.0  -2.0  1.0  -1.0
 -1.0  -1.0  2.0  -1.0
 -1.0  -1.0  1.0  -2.0

In [54]:
?diagm

search: diagm spdiagm diag diagind Diagonal isdiag Bidiagonal blkdiag



```
diagm(v[, k])
```

Construct a diagonal matrix and place `v` on the `k`th diagonal.
